// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAifwYFUK8pQz61SnWGhFk2RbuQUx_wTJ8',
    appId: '1:1056530990131:web:3ebe7cd67a897eef5f8f46',
    messagingSenderId: '1056530990131',
    projectId: 'universidades-feb26',
    authDomain: 'universidades-feb26.firebaseapp.com',
    storageBucket: 'universidades-feb26.firebasestorage.app',
    measurementId: 'G-MPNXZMKHX8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaLZkI2rCGbmCJ7K_Y7Z0CYj41W8rjMV8',
    appId: '1:1056530990131:android:dbcfdf3053a6da7d5f8f46',
    messagingSenderId: '1056530990131',
    projectId: 'universidades-feb26',
    storageBucket: 'universidades-feb26.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATyBw6A9K1rPP0-BwkDTJP0ntnrB08Sqc',
    appId: '1:1056530990131:ios:e6d081377c938ac75f8f46',
    messagingSenderId: '1056530990131',
    projectId: 'universidades-feb26',
    storageBucket: 'universidades-feb26.firebasestorage.app',
    iosBundleId: 'com.example.taller1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATyBw6A9K1rPP0-BwkDTJP0ntnrB08Sqc',
    appId: '1:1056530990131:ios:e6d081377c938ac75f8f46',
    messagingSenderId: '1056530990131',
    projectId: 'universidades-feb26',
    storageBucket: 'universidades-feb26.firebasestorage.app',
    iosBundleId: 'com.example.taller1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAifwYFUK8pQz61SnWGhFk2RbuQUx_wTJ8',
    appId: '1:1056530990131:web:b5cda832c1df58dc5f8f46',
    messagingSenderId: '1056530990131',
    projectId: 'universidades-feb26',
    authDomain: 'universidades-feb26.firebaseapp.com',
    storageBucket: 'universidades-feb26.firebasestorage.app',
    measurementId: 'G-EJ6F6B71YN',
  );

}